// scan-dir/frontend/src/View.vue
<template>
  <div class="rx-page rx-fade-in">
    <header class="rx-head">
      <div>
        <div class="rx-eyebrow">扫描探测 · DIRSCAN</div>
        <h1>目录扫描</h1>
        <p class="rx-sub"><code>scan-dir</code> 模块 · ffuf 风格多字典、FUZZ 多关键字、软404过滤、递归扫描、备份衍生</p>
      </div>
    </header>

    <div class="rx-card" style="margin-bottom:18px">
      <div class="rx-card-head">
        <h3>发起目录扫描</h3>
        <span class="rx-right rx-mono" style="font-size:12px">
          {{ selDict ? selDict.label + '（' + selDict.count.toLocaleString() + ' 条）' : '加载字典…' }}
        </span>
      </div>
      <div class="rx-card-pad">
        <textarea v-model="targets" class="rx-input ds-targets" rows="3" :disabled="running"
          placeholder="目标，每行一个：https://example.com 或 example.com/app&#10;支持 FUZZ 关键字：https://x.com/api/FUZZ?id=1"></textarea>

        <div class="ds-opts">
          <label class="ds-opt">字典
            <select v-model="wordlist" :disabled="running" class="rx-input">
              <option v-for="d in dicts" :key="d.id" :value="d.id">{{ d.label }}（{{ d.count.toLocaleString() }}）</option>
              <option value="custom">自定义词条</option>
            </select>
          </label>
          <label class="ds-opt" title="替换字典中的 %EXT% 占位符，并对目录型词条追加">扩展名
            <input v-model="extensions" :disabled="running" placeholder="php,bak,zip,txt" class="rx-input" style="width:160px" />
          </label>
          <label class="ds-opt">方法
            <select v-model="method" :disabled="running" class="rx-input">
              <option v-for="m in METHODS" :key="m" :value="m">{{ m }}</option>
            </select>
          </label>
          <label class="ds-opt">递归深度
            <input v-model.number="recursion" type="number" min="0" max="3" :disabled="running" class="rx-input ds-num" />
          </label>
          <label class="ds-opt" title="ffuf -x">代理
            <input v-model="proxy" :disabled="running" placeholder="http://127.0.0.1:8080" class="rx-input" style="width:200px" />
          </label>
          <label class="ds-opt" title="自动拼为 Cookie: <value>">Cookie
            <input v-model="cookie" :disabled="running" placeholder="session=abc123; token=xyz" class="rx-input" style="width:200px" />
          </label>
          <label class="ds-opt" title="留空使用内置随机 UA 池">UA
            <input v-model="userAgent" :disabled="running" placeholder="留空=默认" class="rx-input" style="width:180px" />
          </label>
        </div>

        <div class="ds-subhead">自定义请求头（每行一个 <code>Key: Value</code>，支持 FUZZ 占位符）</div>
        <textarea v-model="customHeaders" class="rx-input ds-headers" rows="2" :disabled="running"
          placeholder="Authorization: Bearer eyJhbGci...&#10;X-Forwarded-For: 127.0.0.1&#10;X-Custom-Header: FUZZ"></textarea>

        <textarea v-if="method !== 'GET' && method !== 'HEAD'" v-model="requestBody"
          class="rx-input ds-headers" rows="2" :disabled="running"
          placeholder="请求体（非 GET/HEAD 时发送，可含 FUZZ，如 user=admin&pass=FUZZ）"></textarea>

        <textarea v-if="wordlist === 'custom'" v-model="customWords"
          class="rx-input ds-headers" rows="3" :disabled="running"
          placeholder="自定义词条，每行一个路径名（如 admin、api/v1、backup.zip）"></textarea>

        <!-- 多关键字 FUZ2Z -->
        <div class="ds-opts" style="margin-top:8px">
          <span class="ds-subhead" style="margin:0" title="目标/请求体/请求头里用 FUZ2Z 标记第二位置">多关键字（FUZ2Z）：</span>
          <label class="ds-opt">第二字典
            <select v-model="wordlist2" :disabled="running" class="rx-input">
              <option value="none">不启用</option>
              <option v-for="d in dicts" :key="d.id" :value="d.id">{{ d.label }}</option>
              <option value="custom">自定义</option>
            </select>
          </label>
          <label v-if="wordlist2 !== 'none'" class="ds-opt">模式
            <select v-model="fuzzMode" :disabled="running" class="rx-input">
              <option value="clusterbomb">clusterbomb（N×M）</option>
              <option value="pitchfork">pitchfork（并行）</option>
            </select>
          </label>
        </div>
        <textarea v-if="wordlist2 === 'custom'" v-model="customWords2"
          class="rx-input ds-headers" rows="2" :disabled="running"
          placeholder="第二字典词条（FUZ2Z），每行一个"></textarea>

        <!-- 并发/速率/超时/状态码 -->
        <div class="ds-opts" style="margin-top:8px">
          <label class="ds-opt">并发
            <input v-model.number="concurrency" type="number" min="1" max="64" :disabled="running" class="rx-input ds-num" />
          </label>
          <label class="ds-opt">限速/s
            <input v-model.number="rateLimit" type="number" min="0" max="2000" :disabled="running" class="rx-input ds-num" />
          </label>
          <label class="ds-opt">超时ms
            <input v-model.number="timeout" type="number" min="500" max="30000" :disabled="running" class="rx-input ds-num" style="width:90px" />
          </label>
          <label class="ds-opt">仅保留码
            <input v-model="statusInclude" :disabled="running" placeholder="留空=全部" class="rx-input ds-num" style="width:96px" />
          </label>
          <label class="ds-opt">排除码
            <input v-model="statusExclude" :disabled="running" placeholder="404" class="rx-input ds-num" style="width:80px" />
          </label>
          <label class="ds-opt ds-check">
            <input v-model="followRedirect" type="checkbox" :disabled="running" /> 跟随跳转
          </label>
        </div>

        <!-- ffuf 过滤 -->
        <div class="ds-opts" style="margin-top:8px">
          <span class="ds-subhead" style="margin:0">ffuf 过滤（命中后剔除）：</span>
          <label class="ds-opt" title="ffuf -fs">大小
            <input v-model="filterLength" :disabled="running" placeholder="0,1234" class="rx-input ds-num" style="width:88px" />
          </label>
          <label class="ds-opt" title="ffuf -fw">词数
            <input v-model="filterWords" :disabled="running" placeholder="10,42" class="rx-input ds-num" style="width:72px" />
          </label>
          <label class="ds-opt" title="ffuf -fl">行数
            <input v-model="filterLines" :disabled="running" placeholder="1,7" class="rx-input ds-num" style="width:72px" />
          </label>
          <label class="ds-opt" title="ffuf -fr 正文过滤正则">正文过滤
            <input v-model="filterRegex" :disabled="running" placeholder="Access Denied|无权限" class="rx-input" style="width:160px" />
          </label>
          <label class="ds-opt" title="ffuf -mr 仅保留正文匹配者">正文匹配
            <input v-model="matchRegex" :disabled="running" placeholder="admin|console" class="rx-input" style="width:140px" />
          </label>
          <label class="ds-opt ds-check">
            <input v-model="crawl" type="checkbox" :disabled="running" /> 链接抽取
          </label>
          <label class="ds-opt ds-check">
            <input v-model="collectBackups" type="checkbox" :disabled="running" /> 备份衍生
          </label>
          <label class="ds-opt ds-check">
            <input v-model="randomAgent" type="checkbox" :disabled="running" /> 随机 UA
          </label>
        </div>

        <!-- 操作按钮 -->
        <div class="ds-opts" style="margin-top:12px">
          <button v-if="!running" class="rx-btn rx-btn-primary" :disabled="!targetList.length" @click="start">▸ 发起扫描</button>
          <button v-else class="rx-btn rx-btn-danger" @click="stop">■ 停止扫描</button>
          <button v-if="!running && scan.resumable" class="rx-btn rx-btn-ghost" @click="resume" title="从上次中断处继续">⟳ 续扫</button>
          <span class="rx-spacer"></span>
          <button class="rx-btn rx-btn-ghost" :disabled="!hits.length" @click="exportAs('json')">⭳ JSON</button>
          <button class="rx-btn rx-btn-ghost" :disabled="!hits.length" @click="exportAs('csv')">⭳ CSV</button>
          <button class="rx-btn rx-btn-ghost" :disabled="!hits.length" @click="exportAs('html')">⭳ 报告</button>
        </div>

        <div v-if="running || scan.probed > 0" class="pt-progress">
          <div class="pt-bar"><span :style="{ width: pct + '%' }"></span></div>
          <div class="pt-prog-meta rx-mono">
            <span>{{ running ? '扫描中' : '已完成' }} · {{ scan.phase || '' }} {{ scan.target ? '· ' + scan.target : '' }}</span>
            <span>{{ scan.probed }} / {{ scan.total || '?' }} · 命中 <b style="color:var(--rx-cyan)">{{ scan.found }}</b> · {{ pct }}%</span>
          </div>
          <div v-if="scan.err" class="rx-error" style="margin-top:8px">{{ scan.err }}</div>
        </div>
      </div>
    </div>

    <section class="rx-grid rx-cols-4" style="margin-bottom:18px">
      <div class="rx-stat">
        <div class="rx-stat-label">命中路径</div>
        <div class="rx-stat-val">{{ hits.length || '—' }}</div>
      </div>
      <div class="rx-stat rx-red">
        <div class="rx-stat-label">高危命中</div>
        <div class="rx-stat-val">{{ highCount || '—' }}</div>
      </div>
      <div class="rx-stat">
        <div class="rx-stat-label">已过滤</div>
        <div class="rx-stat-val">{{ scan.filtered ?? '—' }}</div>
      </div>
      <div class="rx-stat rx-purple">
        <div class="rx-stat-label">字典词条</div>
        <div class="rx-stat-val" style="font-size:14px">{{ selDict ? selDict.count.toLocaleString() : (wordlist === 'custom' ? '自定义' : '—') }}</div>
      </div>
    </section>

    <div class="rx-card">
      <div class="rx-card-head">
        <h3>命中路径（{{ sortedHits.length }}）</h3>
        <span class="rx-right">
          <input v-model="q" class="rx-input" placeholder="过滤路径/类型/状态码…" style="width:200px" />
        </span>
      </div>
      <table class="rx-table">
        <thead>
          <tr><th>敏感度</th><th>状态</th><th>路径</th><th>长度</th><th>词/行</th><th>跳转 / 类型</th><th></th></tr>
        </thead>
        <tbody>
          <tr v-for="(h, i) in filtered" :key="h.url+'/'+i">
            <td>
              <span v-if="h.severity && h.severity !== 'info'" class="rx-badge" :class="sevClass(h.severity)">{{ h.severity }}</span>
              <span v-else class="rx-dim">—</span>
            </td>
            <td class="mono" :class="codeClass(h.status)" style="font-weight:600">{{ h.status }}</td>
            <td class="mono" style="color:var(--rx-mid)">
              {{ h.isDir ? '📁 ' : '' }}{{ h.path }}
              <span v-if="h.kind" class="rx-dim" style="font-size:11px;margin-left:6px">{{ h.kind }}</span>
            </td>
            <td class="mono rx-dim" style="font-size:12px">{{ fmtLen(h.length) }}</td>
            <td class="mono rx-dim" style="font-size:12px">{{ h.words }}/{{ h.lines }}</td>
            <td class="mono rx-dim" style="font-size:11px;max-width:200px;overflow:hidden;text-overflow:ellipsis">{{ h.redirect || h.contentType || '—' }}</td>
            <td>
              <a :href="h.url" target="_blank" rel="noreferrer" class="rx-dim" style="font-size:13px" title="在浏览器中打开">↗</a>
            </td>
          </tr>
          <tr v-if="!filtered.length">
            <td colspan="7" class="rx-empty">{{ running ? '扫描中，正在发现命中路径…' : '暂无命中（填写目标后点「发起扫描」）' }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
declare const RedOps: any
const MID = 'scan-dir'

const METHODS = ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']

const targets = ref('')
const wordlist = ref('common')
const customWords = ref('')
const wordlist2 = ref('none')
const customWords2 = ref('')
const fuzzMode = ref<'clusterbomb' | 'pitchfork'>('clusterbomb')
const extensions = ref('')
const concurrency = ref(20)
const rateLimit = ref(0)
const timeout = ref(8000)
const statusInclude = ref('')
const statusExclude = ref('404')
const filterLength = ref('')
const filterWords = ref('')
const filterLines = ref('')
const filterRegex = ref('')
const matchRegex = ref('')
const prefixes = ref('')
const suffixes = ref('')
const crawl = ref(false)
const collectBackups = ref(false)
const randomAgent = ref(false)
const followRedirect = ref(false)
const recursion = ref(0)
const method = ref('GET')
const requestBody = ref('')
const proxy = ref('')
const cookie = ref('')
const userAgent = ref('')
const customHeaders = ref('')
const q = ref('')

interface Hit {
  url: string; path: string; status: number; length: number
  words: number; lines: number; redirect: string; contentType: string
  depth: number; isDir: boolean; severity: string; kind: string
}
interface DictEntry { id: string; label: string; source: string; count: number }
interface ScanStatus {
  running: boolean; phase: string; total: number; probed: number; found: number
  filtered: number; rate: number; target: string; err: string; resumable: boolean; elapsedMs: number
}

const hits = ref<Hit[]>([])
const dicts = ref<DictEntry[]>([])
const scan = ref<ScanStatus>({ running: false, phase: '', total: 0, probed: 0, found: 0, filtered: 0, rate: 0, target: '', err: '', resumable: false, elapsedMs: 0 })
let timer: any = null

const SEV_RANK: Record<string, number> = { critical: 5, high: 4, medium: 3, low: 2, info: 1 }
const running = computed(() => scan.value.running)
const targetList = computed(() => targets.value.split('\n').map(s => s.trim()).filter(Boolean))
const highCount = computed(() => hits.value.filter(h => h.severity === 'critical' || h.severity === 'high').length)
const selDict = computed(() => dicts.value.find(d => d.id === wordlist.value))
const pct = computed(() => scan.value.total > 0 ? Math.min(100, Math.round(scan.value.probed / scan.value.total * 100)) : (scan.value.running ? 0 : 100))
const sortedHits = computed(() => [...hits.value].sort((a, b) => (SEV_RANK[b.severity] ?? 1) - (SEV_RANK[a.severity] ?? 1)))
const filtered = computed(() => {
  const kw = q.value.trim().toLowerCase()
  if (!kw) return sortedHits.value
  return sortedHits.value.filter(h => [h.path, h.url, String(h.status), h.kind || '', h.contentType || ''].join(' ').toLowerCase().includes(kw))
})

function codeClass(code: number): string {
  if (code >= 200 && code < 300) return 'ds-code-ok'
  if (code >= 300 && code < 400) return 'ds-code-redirect'
  if (code >= 400 && code < 500) return 'ds-code-warn'
  if (code >= 500) return 'ds-code-err'
  return 'rx-dim'
}
function sevClass(sev: string): string {
  return ({ critical: 'rx-crit', high: 'rx-crit', medium: 'rx-med', low: 'rx-low', info: 'rx-info' } as any)[sev] ?? 'rx-info'
}
function fmtLen(n: number): string {
  if (n >= 1024 * 1024) return (n / 1024 / 1024).toFixed(1) + 'M'
  if (n >= 1024) return (n / 1024).toFixed(1) + 'K'
  return String(n)
}

async function refresh() {
  try {
    const [st, h] = await Promise.all([
      RedOps.api(MID, '/scan/status').then((r: Response) => r.json()),
      RedOps.api(MID, '/hits').then((r: Response) => r.json()),
    ])
    scan.value = st.status ?? scan.value
    hits.value = h.items ?? []
  } catch { /* ignore */ }
}

function poll() {
  if (timer) clearTimeout(timer)
  const tick = async () => {
    await refresh()
    if (scan.value.running) { timer = setTimeout(tick, 1500) } else { timer = null }
  }
  timer = setTimeout(tick, 800)
}

async function start() {
  if (!targetList.value.length) { RedOps?.toast?.('请先填写扫描目标', 'warn'); return }
  const words = customWords.value.split('\n').map(s => s.trim()).filter(Boolean)
  if (wordlist.value === 'custom' && !words.length) { RedOps?.toast?.('字典选择了「自定义」，请填写词条', 'warn'); return }
  try {
    const words2 = customWords2.value.split('\n').map(s => s.trim()).filter(Boolean)
    const extraHeaders = customHeaders.value.split('\n').map(s => s.trim()).filter(Boolean)
    if (cookie.value.trim()) extraHeaders.push(`Cookie: ${cookie.value.trim()}`)
    const res = await RedOps.api(MID, '/scan', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        targets: targetList.value, wordlist: wordlist.value, customWords: words, extensions: extensions.value,
        wordlist2: wordlist2.value === 'none' ? '' : wordlist2.value, customWords2: words2, fuzzMode: fuzzMode.value,
        concurrency: concurrency.value, rate: rateLimit.value, timeout: timeout.value,
        statusInclude: statusInclude.value, statusExclude: statusExclude.value,
        filterLength: filterLength.value, filterWords: filterWords.value, filterLines: filterLines.value,
        filterRegex: filterRegex.value, matchRegex: matchRegex.value,
        prefixes: prefixes.value, suffixes: suffixes.value,
        crawl: crawl.value, collectBackups: collectBackups.value, randomAgent: randomAgent.value,
        followRedirect: followRedirect.value, recursion: recursion.value, method: method.value,
        requestBody: requestBody.value, proxy: proxy.value, userAgent: userAgent.value, headers: extraHeaders,
      }),
    })
    if (res.status === 409) { RedOps?.toast?.('已有扫描在运行', 'warn'); return }
    if (!res.ok) { const j = await res.json().catch(() => ({})); RedOps?.toast?.(j.error || '发起失败', 'err'); return }
    const j = await res.json()
    scan.value = j.status ?? scan.value
    hits.value = []
    RedOps?.toast?.(`已对 ${targetList.value.length} 个目标发起扫描`, 'ok')
    poll()
  } catch (e: any) { RedOps?.toast?.('发起失败: ' + (e?.message ?? e), 'err') }
}

async function stop() {
  try { await RedOps.api(MID, '/scan/stop', { method: 'POST' }); RedOps?.toast?.('已请求停止', 'warn') } catch { /* ignore */ }
}

async function resume() {
  try {
    const res = await RedOps.api(MID, '/scan/resume', { method: 'POST' })
    if (res.status === 409) { RedOps?.toast?.('已有扫描在运行', 'warn'); return }
    if (!res.ok) { const j = await res.json().catch(() => ({})); RedOps?.toast?.(j.error || '续扫失败', 'err'); return }
    const j = await res.json()
    scan.value = j.status ?? scan.value
    RedOps?.toast?.('已继续上次未完成的扫描', 'ok')
    poll()
  } catch (e: any) { RedOps?.toast?.('续扫失败: ' + (e?.message ?? e), 'err') }
}

async function exportAs(fmt: string) {
  try {
    const res = await RedOps.api(MID, `/export?format=${fmt}`)
    if (!res.ok) { RedOps?.toast?.('导出失败', 'err'); return }
    const blob = await res.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = `dirscan.${fmt}`
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url)
    RedOps?.toast?.(`已导出 ${fmt.toUpperCase()}`, 'ok')
  } catch (e: any) { RedOps?.toast?.('导出失败: ' + (e?.message ?? e), 'err') }
}

onMounted(async () => {
  try { const d = await RedOps.api(MID, '/dict').then((r: Response) => r.json()); dicts.value = d.lists ?? [] } catch { /* ignore */ }
  await refresh()
  if (scan.value.running) poll()
})
onUnmounted(() => { if (timer) clearTimeout(timer) })
</script>

<style scoped>
.ds-targets, .ds-headers { width: 100%; resize: vertical; font-family: 'JetBrains Mono', ui-monospace, monospace; font-size: 12.5px; line-height: 1.6; }
.ds-headers { margin-top: 8px; }
.ds-opts { display: flex; align-items: center; gap: 12px; margin-top: 10px; flex-wrap: wrap; }
.ds-opt { display: flex; align-items: center; gap: 8px; font-size: 12.5px; color: var(--rx-mid, #94a3b8); }
.ds-num { width: 80px; }
.ds-check { cursor: pointer; }
.ds-check input { accent-color: var(--rx-cyan, #22d3ee); }
.ds-subhead { font-size: 11.5px; color: var(--rx-dim, #6b7689); margin-top: 10px; margin-bottom: 4px; }
.rx-btn-danger { background: rgba(244, 63, 94, .14); border-color: rgba(244, 63, 94, .4); color: #fda4af; }
.rx-btn-ghost { background: rgba(34, 211, 238, .08); border-color: rgba(34, 211, 238, .28); color: #7dd3fc; font-size: 12px; padding: 5px 10px; }
.rx-btn-ghost:disabled { opacity: .4; cursor: not-allowed; }
.pt-progress { margin-top: 14px; }
.pt-bar { height: 8px; border-radius: 5px; background: rgba(7, 10, 16, .6); overflow: hidden; border: 1px solid var(--rx-line, #1d2533); }
.pt-bar span { display: block; height: 100%; background: linear-gradient(90deg, #22d3ee, #6366f1); transition: width .4s ease; }
.pt-prog-meta { display: flex; justify-content: space-between; font-size: 11.5px; color: var(--rx-dim, #6b7689); margin-top: 6px; }
.ds-code-ok { color: #4ade80; }
.ds-code-redirect { color: var(--rx-cyan, #22d3ee); }
.ds-code-warn { color: #fb923c; }
.ds-code-err { color: #f87171; }
</style>

// scan-dir/web/View.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import {
  FolderSearch, FileSearch, FolderTree, Filter, Play, Square, RefreshCw, Download, ExternalLink,
} from 'lucide-react'
import { Panel, StatCard, Progress, SeverityTag } from '@/components/ui'
import type { Severity } from '@/types'
import { engineGet, enginePost, engineDownload } from '@/lib/engine'
import { ApiError } from '@/lib/api'
import { createTask, updateTask } from '@/lib/tasks'
import TaskList from '@/components/TaskList'

const CAP = 'scan-dir'

interface Hit {
  url: string
  path: string
  status: number
  length: number
  words: number
  lines: number
  redirect: string
  contentType: string
  depth: number
  isDir: boolean
  severity: Severity
  kind: string
}

const SEV_RANK: Record<string, number> = { critical: 5, high: 4, medium: 3, low: 2, info: 1 }

interface ScanStatus {
  running: boolean
  phase: string
  total: number
  probed: number
  found: number
  filtered: number
  rate: number
  elapsedMs: number
  target: string
  startedAt: string
  endedAt: string
  err: string
  resumable: boolean
}

type Method = 'GET' | 'HEAD' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS'
const METHODS: Method[] = ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']

interface DictEntry {
  id: string
  label: string
  source: string
  count: number
}

// 状态码配色：2xx 绿 / 3xx 青 / 4xx 橙 / 5xx 红。
function codeClass(code: number): string {
  if (code >= 200 && code < 300) return 'text-sev-low'
  if (code >= 300 && code < 400) return 'text-cyber'
  if (code >= 400 && code < 500) return 'text-sev-medium'
  if (code >= 500) return 'text-sev-high'
  return 'text-slate-400'
}

function fmtLen(n: number): string {
  if (n >= 1024 * 1024) return (n / 1024 / 1024).toFixed(1) + 'M'
  if (n >= 1024) return (n / 1024).toFixed(1) + 'K'
  return String(n)
}

export default function View() {
  const [status, setStatus] = useState<ScanStatus | null>(null)
  const [hits, setHits] = useState<Hit[]>([])
  const [dicts, setDicts] = useState<DictEntry[]>([])

  const [targets, setTargets] = useState('')
  const [wordlist, setWordlist] = useState<string>('common')
  const [customWords, setCustomWords] = useState('')
  const [wordlist2, setWordlist2] = useState<string>('none')
  const [customWords2, setCustomWords2] = useState('')
  const [fuzzMode, setFuzzMode] = useState<'clusterbomb' | 'pitchfork'>('clusterbomb')
  const [extensions, setExtensions] = useState('')
  const [concurrency, setConcurrency] = useState(20)
  const [rate, setRate] = useState(0)
  const [timeout, setTimeoutMs] = useState(8000)
  const [statusInclude, setStatusInclude] = useState('')
  const [statusExclude, setStatusExclude] = useState('404')
  const [filterLength, setFilterLength] = useState('')
  const [filterWords, setFilterWords] = useState('')
  const [filterLines, setFilterLines] = useState('')
  const [filterRegex, setFilterRegex] = useState('')
  const [matchRegex, setMatchRegex] = useState('')
  const [minLength, setMinLength] = useState(0)
  const [maxLength, setMaxLength] = useState(0)
  const [prefixes, setPrefixes] = useState('')
  const [suffixes, setSuffixes] = useState('')
  const [crawl, setCrawl] = useState(false)
  const [collectBackups, setCollectBackups] = useState(false)
  const [randomAgent, setRandomAgent] = useState(false)
  const [followRedirect, setFollowRedirect] = useState(false)
  const [recursion, setRecursion] = useState(0)
  const [method, setMethod] = useState<Method>('GET')
  const [requestBody, setRequestBody] = useState('')
  const [proxy, setProxy] = useState('')
  const [cookie, setCookie] = useState('')
  const [userAgent, setUserAgent] = useState('')
  const [customHeaders, setCustomHeaders] = useState('')

  const [err, setErr] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [taskReload, setTaskReload] = useState(0)
  const timer = useRef<ReturnType<typeof setInterval> | null>(null)

  const refresh = useCallback(async () => {
    const [st, h] = await Promise.all([
      engineGet<{ status: ScanStatus; id: string }>(CAP, '/scan/status'),
      engineGet<{ items: Hit[] }>(CAP, '/hits'),
    ])
    setStatus(st.status)
    setHits(h.items ?? [])
    return st.status
  }, [])

  // 仅在扫描运行时轮询实时进度/命中（界面展示）。任务台账的进度/结果固化由
  // 后端 reconcile-on-read 负责（读取任务时按 task_id 拉引擎落库结果），本端不镜像。
  const startPolling = useCallback(() => {
    if (timer.current) return
    timer.current = setInterval(async () => {
      try {
        const st = await refresh()
        if (!st.running && timer.current) {
          clearInterval(timer.current); timer.current = null
          setTaskReload((n) => n + 1)
        }
      } catch { /* 轮询瞬时错误忽略 */ }
    }, 1500)
  }, [refresh])

  useEffect(() => {
    refresh().then((st) => { if (st.running) startPolling() }).catch((e) => setErr(String(e?.message ?? e)))
    engineGet<{ lists: DictEntry[] }>(CAP, '/dict').then((d) => setDicts(d.lists ?? [])).catch(() => {})
    return () => { if (timer.current) clearInterval(timer.current) }
  }, [refresh, startPolling])

  async function call(fn: () => Promise<unknown>) {
    setBusy(true); setErr(null)
    try { await fn(); await refresh() }
    catch (e) { setErr(e instanceof ApiError ? e.message : String((e as Error)?.message ?? e)) }
    finally { setBusy(false) }
  }

  async function startScan() {
    const list = targets.split('\n').map((t) => t.trim()).filter(Boolean)
    if (!list.length) { setErr('请填写至少一个目标（http(s) URL / 域名 / IP，每行一个）'); return }
    const words = customWords.split('\n').map((t) => t.trim()).filter(Boolean)
    if (wordlist === 'custom' && !words.length) { setErr('字典选择了「自定义」，请填写词条'); return }
    await call(async () => {
      const words2 = customWords2.split('\n').map((t) => t.trim()).filter(Boolean)
      // Merge cookie and custom headers into a single headers list (backend format: "Key: Value").
      const extraHeaders = customHeaders.split('\n').map((h) => h.trim()).filter(Boolean)
      if (cookie.trim()) extraHeaders.push(`Cookie: ${cookie.trim()}`)
      const params = {
        targets: list, wordlist, customWords: words, extensions,
        wordlist2: wordlist2 === 'none' ? '' : wordlist2, customWords2: words2, fuzzMode,
        concurrency, rate, timeout, statusInclude, statusExclude,
        filterLength, filterWords, filterLines, filterRegex, matchRegex,
        minLength, maxLength, prefixes, suffixes,
        crawl, collectBackups, randomAgent, followRedirect, recursion, method,
        requestBody, proxy, userAgent, headers: extraHeaders,
      }
      // 统一 task_id：先向系统申请 id 落台账，再透传给引擎 /invoke。
      const t = await createTask({ capabilityKey: CAP, action: 'scan', params })
      setTaskReload((n) => n + 1)
      try {
        await enginePost(CAP, '/invoke', { taskId: t.id, function: 'scan', params })
      } catch (e) {
        await updateTask(t.id, {
          status: 'failed', error: e instanceof Error ? e.message : String(e),
        }).catch(() => {})
        setTaskReload((n) => n + 1)
        throw e
      }
      startPolling()
    })
  }

  const running = status?.running ?? false
  const pct = status && status.total > 0 ? Math.min(100, Math.round((status.probed / status.total) * 100)) : 0
  const highValue = hits.filter((h) => h.severity === 'critical' || h.severity === 'high').length
  const selDict = dicts.find((d) => d.id === wordlist)
  // 展示用:按敏感度降序、同级保持发现顺序。
  const sortedHits = [...hits].sort((a, b) => (SEV_RANK[b.severity] ?? 1) - (SEV_RANK[a.severity] ?? 1))

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard label="命中路径" value={hits.length || '—'} icon={<FileSearch size={18} />} />
        <StatCard label="高危命中" value={highValue || '—'} icon={<FolderTree size={18} />} />
        <StatCard label="已过滤" value={status?.filtered ?? '—'} icon={<Filter size={18} />} />
        <StatCard label="字典词条" value={selDict ? selDict.count.toLocaleString() : (wordlist === 'custom' ? '自定义' : '—')} icon={<FolderSearch size={18} />} />
      </div>

      <Panel title="发起目录扫描" icon={<FolderSearch size={16} />}>
        <div className="space-y-3">
          <textarea
            className="w-full rounded-lg border border-line bg-base-700/60 p-3 font-mono text-sm text-slate-200 outline-none focus:border-cyber"
            rows={3} placeholder="目标，每行一个：https://example.com 或 example.com/app 或 含 FUZZ 关键字（ffuf 风格）如 https://x.com/api/FUZZ?id=1"
            value={targets} onChange={(e) => setTargets(e.target.value)} disabled={running}
          />
          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <label className="flex items-center gap-2">字典
              <select value={wordlist} onChange={(e) => setWordlist(e.target.value)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                {dicts.map((d) => (
                  <option key={d.id} value={d.id}>{d.label}（{d.count.toLocaleString()}）</option>
                ))}
                <option value="custom">自定义词条</option>
              </select>
            </label>
            <label className="flex items-center gap-2" title="替换字典中的 %EXT% 占位符，并对目录型词条追加">扩展名
              <input value={extensions} onChange={(e) => setExtensions(e.target.value)} disabled={running}
                placeholder="php,bak,zip,txt（%EXT%）"
                className="w-44 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">方法
              <select value={method} onChange={(e) => setMethod(e.target.value as Method)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                {METHODS.map((m) => <option key={m} value={m}>{m}</option>)}
              </select>
            </label>
            <label className="flex items-center gap-2">递归
              <input type="number" min={0} max={3} value={recursion}
                onChange={(e) => setRecursion(+e.target.value)} disabled={running}
                className="w-16 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="ffuf -x / dirsearch --proxy">代理
              <input value={proxy} onChange={(e) => setProxy(e.target.value)} disabled={running}
                placeholder="http://127.0.0.1:8080"
                className="w-52 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="附加 Cookie：自动拼为 Cookie: <value> 请求头">Cookie
              <input value={cookie} onChange={(e) => setCookie(e.target.value)} disabled={running}
                placeholder="session=abc123; token=xyz"
                className="w-56 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="留空使用内置随机 UA 池">UA
              <input value={userAgent} onChange={(e) => setUserAgent(e.target.value)} disabled={running}
                placeholder="留空=默认"
                className="w-56 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
          </div>

          {/* 自定义请求头 */}
          <div className="space-y-1">
            <label className="flex items-center gap-1 text-xs text-slate-500" title="每行一个 Key: Value，可用 FUZZ 占位符做请求头 Fuzz">
              自定义请求头（每行一个 <code className="font-mono">Key: Value</code>，支持 FUZZ 占位符）
            </label>
            <textarea
              className="w-full rounded-lg border border-line bg-base-700/60 p-2 font-mono text-xs text-slate-200 outline-none focus:border-cyber"
              rows={2}
              placeholder={"Authorization: Bearer eyJhbGci...\nX-Forwarded-For: 127.0.0.1\nX-Custom-Header: FUZZ"}
              value={customHeaders} onChange={(e) => setCustomHeaders(e.target.value)} disabled={running}
            />
          </div>

          {method !== 'GET' && method !== 'HEAD' && (
            <textarea
              className="w-full rounded-lg border border-line bg-base-700/60 p-3 font-mono text-xs text-slate-200 outline-none focus:border-cyber"
              rows={2} placeholder="请求体（ffuf -d）：非 GET/HEAD 时发送，可含 FUZZ，如 user=admin&pass=FUZZ"
              value={requestBody} onChange={(e) => setRequestBody(e.target.value)} disabled={running}
            />
          )}

          {wordlist === 'custom' && (
            <textarea
              className="w-full rounded-lg border border-line bg-base-700/60 p-3 font-mono text-xs text-slate-200 outline-none focus:border-cyber"
              rows={3} placeholder="自定义词条，每行一个路径名（如 admin、api/v1、backup.zip）"
              value={customWords} onChange={(e) => setCustomWords(e.target.value)} disabled={running}
            />
          )}

          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <span className="text-xs text-slate-500" title="ffuf 多关键字：目标/请求体/请求头里用 FUZ2Z 标记第二位置">多关键字（FUZ2Z）：</span>
            <label className="flex items-center gap-2">第二字典
              <select value={wordlist2} onChange={(e) => setWordlist2(e.target.value)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                <option value="none">不启用</option>
                {dicts.map((d) => <option key={d.id} value={d.id}>{d.label}（{d.count.toLocaleString()}）</option>)}
                <option value="custom">自定义词条</option>
              </select>
            </label>
            {wordlist2 !== 'none' && (
              <label className="flex items-center gap-2">模式
                <select value={fuzzMode} onChange={(e) => setFuzzMode(e.target.value as 'clusterbomb' | 'pitchfork')} disabled={running}
                  className="rounded border border-line bg-base-700/60 px-2 py-1">
                  <option value="clusterbomb">clusterbomb（N×M）</option>
                  <option value="pitchfork">pitchfork（并行）</option>
                </select>
              </label>
            )}
          </div>
          {wordlist2 === 'custom' && (
            <textarea
              className="w-full rounded-lg border border-line bg-base-700/60 p-3 font-mono text-xs text-slate-200 outline-none focus:border-cyber"
              rows={2} placeholder="第二字典词条（FUZ2Z），每行一个"
              value={customWords2} onChange={(e) => setCustomWords2(e.target.value)} disabled={running}
            />
          )}

          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <label className="flex items-center gap-2">并发
              <input type="number" min={1} max={64} value={concurrency}
                onChange={(e) => setConcurrency(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">限速/s
              <input type="number" min={0} max={2000} value={rate}
                onChange={(e) => setRate(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">超时ms
              <input type="number" min={500} max={30000} value={timeout}
                onChange={(e) => setTimeoutMs(+e.target.value)} disabled={running}
                className="w-24 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">仅保留码
              <input value={statusInclude} onChange={(e) => setStatusInclude(e.target.value)} disabled={running}
                placeholder="留空=全部"
                className="w-32 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">排除码
              <input value={statusExclude} onChange={(e) => setStatusExclude(e.target.value)} disabled={running}
                placeholder="404"
                className="w-24 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={followRedirect} onChange={(e) => setFollowRedirect(e.target.checked)} disabled={running} />
              跟随跳转
            </label>
          </div>

          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <span className="text-xs text-slate-500">ffuf 过滤（命中后剔除匹配项）：</span>
            <label className="flex items-center gap-2" title="ffuf -fs：过滤掉这些响应体字节数">大小
              <input value={filterLength} onChange={(e) => setFilterLength(e.target.value)} disabled={running}
                placeholder="0,1234"
                className="w-24 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="ffuf -fw：过滤掉这些词数">词数
              <input value={filterWords} onChange={(e) => setFilterWords(e.target.value)} disabled={running}
                placeholder="10,42"
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="ffuf -fl：过滤掉这些行数">行数
              <input value={filterLines} onChange={(e) => setFilterLines(e.target.value)} disabled={running}
                placeholder="1,7"
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="dirsearch --minimal / --maximal：响应大小区间(0=不限)">大小区间
              <input type="number" min={0} value={minLength} onChange={(e) => setMinLength(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
              <span className="text-slate-500">~</span>
              <input type="number" min={0} value={maxLength} onChange={(e) => setMaxLength(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
          </div>

          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <label className="flex items-center gap-2" title="ffuf -fr / dirsearch --exclude-texts：正文匹配则剔除">正文过滤
              <input value={filterRegex} onChange={(e) => setFilterRegex(e.target.value)} disabled={running}
                placeholder="Access Denied|无权限"
                className="w-48 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="ffuf -mr：仅保留正文匹配者">正文匹配
              <input value={matchRegex} onChange={(e) => setMatchRegex(e.target.value)} disabled={running}
                placeholder="admin|console"
                className="w-40 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="dirsearch --prefixes：为每词条加前缀">前缀
              <input value={prefixes} onChange={(e) => setPrefixes(e.target.value)} disabled={running}
                placeholder=".,_"
                className="w-24 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="dirsearch --suffixes：为每词条加后缀">后缀
              <input value={suffixes} onChange={(e) => setSuffixes(e.target.value)} disabled={running}
                placeholder="~,.bak,/"
                className="w-28 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2" title="feroxbuster --extract-links / dirsearch --crawl">
              <input type="checkbox" checked={crawl} onChange={(e) => setCrawl(e.target.checked)} disabled={running} />
              链接抽取
            </label>
            <label className="flex items-center gap-2" title="feroxbuster --collect-backups：命中文件时自动探 .bak/~/.old/.swp 等备份变体">
              <input type="checkbox" checked={collectBackups} onChange={(e) => setCollectBackups(e.target.checked)} disabled={running} />
              备份衍生
            </label>
            <label className="flex items-center gap-2" title="dirsearch random-agent">
              <input type="checkbox" checked={randomAgent} onChange={(e) => setRandomAgent(e.target.checked)} disabled={running} />
              随机 UA
            </label>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {running ? (
              <button onClick={() => call(() => enginePost(CAP, '/scan/stop'))} disabled={busy}
                className="chip border border-sev-high/40 bg-sev-high/10 text-sev-high">
                <Square size={14} /> 停止扫描
              </button>
            ) : (
              <>
                <button onClick={startScan} disabled={busy}
                  className="chip border border-cyber/40 bg-cyber/10 text-cyber">
                  <Play size={14} /> 发起扫描
                </button>
                {status?.resumable && (
                  <button onClick={() => call(async () => { await enginePost(CAP, '/scan/resume'); startPolling() })} disabled={busy}
                    className="chip border border-sev-medium/40 bg-sev-medium/10 text-sev-medium"
                    title="从上次中断处继续(保留已有命中,跳过已扫目录)">
                    <RefreshCw size={14} /> 续扫
                  </button>
                )}
              </>
            )}
            <button onClick={() => call(async () => { await refresh() })} disabled={busy}
              className="chip border border-line bg-base-600/60 text-slate-300">
              <RefreshCw size={14} /> 刷新
            </button>
            <div className="ml-auto flex items-center gap-1">
              {(['json', 'csv', 'html'] as const).map((f) => (
                <button key={f} onClick={() => engineDownload(CAP, '/export', `dirscan-hits.${f}`, { format: f })}
                  disabled={hits.length === 0}
                  className="chip border border-line bg-base-600/60 text-slate-400">
                  <Download size={14} /> {f.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          {running && (
            <div className="space-y-1">
              <div className="flex justify-between text-xs text-slate-400">
                <span>{status?.phase || '扫描中…'}　{status?.target}</span>
                <span className="font-mono">{status?.probed}/{status?.total}（命中 {status?.found}）</span>
              </div>
              <Progress value={pct} />
            </div>
          )}
          {err && <div className="text-sm text-sev-high">{err}</div>}
        </div>
      </Panel>

      <Panel title={`命中路径（${hits.length}）`} icon={<FileSearch size={16} />} bodyClass="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-line text-left text-xs text-slate-500">
                <th className="px-4 py-2 font-medium">敏感度</th>
                <th className="px-4 py-2 font-medium">状态</th>
                <th className="px-4 py-2 font-medium">路径</th>
                <th className="px-4 py-2 font-medium">长度</th>
                <th className="px-4 py-2 font-medium">词/行</th>
                <th className="px-4 py-2 font-medium">跳转 / 类型</th>
                <th className="px-4 py-2 font-medium"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {hits.length === 0 && (
                <tr><td colSpan={7} className="p-6 text-center text-sm text-slate-500">暂无命中</td></tr>
              )}
              {sortedHits.map((h, i) => (
                <tr key={`${h.url}/${i}`} className="hover:bg-base-600/40">
                  <td className="px-4 py-2">
                    {h.severity && h.severity !== 'info'
                      ? <SeverityTag severity={h.severity} />
                      : <span className="text-xs text-slate-600">—</span>}
                  </td>
                  <td className={`px-4 py-2 font-mono font-semibold ${codeClass(h.status)}`}>{h.status}</td>
                  <td className="px-4 py-2 font-mono text-slate-300">
                    {h.isDir && <FolderTree size={12} className="mr-1 inline text-cyber" />}
                    {h.path}
                    {h.kind && <span className="ml-2 text-xs text-slate-500">{h.kind}</span>}
                  </td>
                  <td className="px-4 py-2 font-mono text-xs text-slate-400">{fmtLen(h.length)}</td>
                  <td className="px-4 py-2 font-mono text-xs text-slate-500">{h.words}/{h.lines}</td>
                  <td className="px-4 py-2 font-mono text-xs text-slate-500">{h.redirect || h.contentType || '—'}</td>
                  <td className="px-4 py-2">
                    <a href={h.url} target="_blank" rel="noreferrer" className="text-slate-500 hover:text-cyber">
                      <ExternalLink size={14} />
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      <Panel title="历史任务" icon={<FolderSearch size={16} />} bodyClass="p-3">
        <TaskList params={{ capabilityKey: CAP }} showCapability={false} reloadToken={taskReload}
          emptyHint="暂无任务记录，发起一次扫描后将登记到此。" />
      </Panel>
    </div>
  )
}
