// scan-port/frontend/src/View.vue
<template>
  <div class="rx-page rx-fade-in">
    <header class="rx-head">
      <div>
        <div class="rx-eyebrow">扫描探测 · PORTS</div>
        <h1>端口扫描</h1>
        <p class="rx-sub"><code>scan-port</code> 模块 · TCP/UDP/SYN 三模式端口扫描，服务识别，Banner 抓取，主动协议探针</p>
      </div>
    </header>

    <div class="rx-card" style="margin-bottom:18px">
      <div class="rx-card-head">
        <h3>发起端口扫描</h3>
      </div>
      <div class="rx-card-pad">
        <textarea v-model="targets" class="rx-input pt-targets" rows="3" :disabled="running"
          placeholder="目标，每行一个：192.168.1.0/24 或 example.com 或 10.0.0.5"></textarea>

        <div class="pt-opts">
          <label class="pt-opt">端口
            <select v-model="portSpec" :disabled="running" class="rx-input">
              <option value="top100">top100（高频端口）</option>
              <option value="top500">top500（约 370 个）</option>
              <option value="top1000">top1000（推荐）</option>
              <option value="all">全端口（慎用）</option>
              <option value="custom">自定义</option>
            </select>
          </label>
          <label v-if="portSpec === 'custom'" class="pt-opt">自定义端口
            <input v-model="portsCustom" :disabled="running" placeholder="22,80,443,8000-8100" class="rx-input" style="width:180px" />
          </label>
          <label class="pt-opt">引擎
            <select v-model="mode" :disabled="running" class="rx-input">
              <option value="masscan">masscan（高速·需管理员）</option>
              <option value="connect">connect（免提权）</option>
              <option value="syn">SYN（需 npcap）</option>
            </select>
          </label>
          <label class="pt-opt">协议
            <select v-model="proto" :disabled="running" class="rx-input">
              <option value="tcp">TCP</option>
              <option value="udp">UDP</option>
              <option value="both">TCP+UDP</option>
            </select>
          </label>
          <label class="pt-opt">速率
            <input v-model.number="rate" type="number" min="0" max="100000" :disabled="running" class="rx-input pt-num" />
          </label>
          <label class="pt-opt">并发
            <input v-model.number="concurrency" type="number" min="1" max="1024" :disabled="running" class="rx-input pt-num" />
          </label>
          <label class="pt-opt">超时ms
            <input v-model.number="timeout" type="number" min="100" max="10000" :disabled="running" class="rx-input pt-num" />
          </label>
          <label class="pt-opt pt-check">
            <input v-model="discovery" type="checkbox" :disabled="running" /> 存活探测
          </label>
          <label class="pt-opt pt-check">
            <input v-model="svc" type="checkbox" :disabled="running" /> 服务识别
          </label>
          <label class="pt-opt pt-check">
            <input v-model="banner" type="checkbox" :disabled="running" /> 抓取 Banner
          </label>
          <span class="rx-spacer"></span>
          <button v-if="!running" class="rx-btn rx-btn-primary" :disabled="!targetList.length" @click="start">▸ 发起扫描</button>
          <button v-else class="rx-btn rx-btn-danger" @click="stop">■ 停止扫描</button>
          <button class="rx-btn rx-btn-ghost" :disabled="!ports.length" @click="exportAs('json')">⭳ JSON</button>
          <button class="rx-btn rx-btn-ghost" :disabled="!ports.length" @click="exportAs('csv')">⭳ CSV</button>
          <button class="rx-btn rx-btn-ghost" :disabled="!ports.length" @click="exportAs('html')">⭳ 报告</button>
        </div>

        <div v-if="running || scan.probed > 0" class="pt-progress">
          <div class="pt-bar"><span :style="{ width: pct + '%' }"></span></div>
          <div class="pt-prog-meta rx-mono">
            <span>{{ running ? '扫描中' : '已完成' }} · {{ scan.phase || '—' }} {{ scan.target ? '· ' + scan.target : '' }}</span>
            <span>{{ scan.probed }} / {{ scan.total || '?' }} · 开放 <b style="color:var(--rx-cyan)">{{ scan.found }}</b> · {{ pct }}%</span>
          </div>
          <div v-if="scan.err" class="rx-error" style="margin-top:8px">{{ scan.err }}</div>
        </div>
      </div>
    </div>

    <section class="rx-grid rx-cols-4" style="margin-bottom:18px">
      <div class="rx-stat">
        <div class="rx-stat-label">开放端口</div>
        <div class="rx-stat-val">{{ ports.length || '—' }}</div>
      </div>
      <div class="rx-stat">
        <div class="rx-stat-label">涉及主机</div>
        <div class="rx-stat-val">{{ hostCount || '—' }}</div>
      </div>
      <div class="rx-stat">
        <div class="rx-stat-label">TCP / UDP</div>
        <div class="rx-stat-val rx-mono" style="font-size:18px">{{ tcpCount }} / {{ udpCount }}</div>
      </div>
      <div class="rx-stat">
        <div class="rx-stat-label">本次引擎</div>
        <div class="rx-stat-val" style="font-size:14px">{{ scan.engine || '—' }}</div>
      </div>
    </section>

    <div class="rx-card">
      <div class="rx-card-head">
        <h3>开放端口（{{ filtered.length }}）</h3>
        <span class="rx-right">
          <input v-model="q" class="rx-input" placeholder="过滤主机/端口/服务…" style="width:200px" />
        </span>
      </div>
      <table class="rx-table">
        <thead>
          <tr><th>主机</th><th>端口</th><th>协议</th><th>服务</th><th>OS</th><th>Banner</th></tr>
        </thead>
        <tbody>
          <tr v-for="p in filtered" :key="p.host+'/'+p.proto+'/'+p.port">
            <td class="mono">{{ p.host }}</td>
            <td class="mono" style="color:var(--rx-cyan)">{{ p.port }}</td>
            <td><span class="rx-badge rx-info">{{ p.proto }}</span></td>
            <td>{{ p.service || '—' }}</td>
            <td class="rx-dim" style="font-size:12px">{{ p.osGuess || '—' }}</td>
            <td class="mono rx-dim" style="font-size:11px;max-width:320px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ p.banner || '—' }}</td>
          </tr>
          <tr v-if="!filtered.length">
            <td colspan="6" class="rx-empty">{{ running ? '扫描中，正在发现开放端口…' : '暂无开放端口（填写目标后点「发起扫描」）' }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
declare const RedOps: any
const MID = 'scan-port'

const targets = ref('')
const portSpec = ref('top1000')
const portsCustom = ref('22,80,443')
const mode = ref('masscan')
const proto = ref('tcp')
const rate = ref(1000)
const concurrency = ref(256)
const timeout = ref(1500)
const discovery = ref(false)
const svc = ref(true)
const banner = ref(true)
const q = ref('')

interface Port { host: string; port: number; proto: string; service: string; banner: string; osGuess: string }
interface ScanStatus {
  running: boolean; phase: string; total: number; probed: number; found: number
  rate: number; engine: string; target: string; err: string; elapsedMs: number
}

const ports = ref<Port[]>([])
const scan = ref<ScanStatus>({ running: false, phase: '', total: 0, probed: 0, found: 0, rate: 0, engine: '', target: '', err: '', elapsedMs: 0 })
let timer: any = null

const running = computed(() => scan.value.running)
const targetList = computed(() => targets.value.split('\n').map(s => s.trim()).filter(Boolean))
const hostCount = computed(() => new Set(ports.value.map(p => p.host)).size)
const tcpCount = computed(() => ports.value.filter(p => p.proto === 'tcp').length)
const udpCount = computed(() => ports.value.filter(p => p.proto === 'udp').length)
const pct = computed(() => scan.value.total > 0 ? Math.min(100, Math.round(scan.value.probed / scan.value.total * 100)) : (scan.value.running ? 0 : 100))
const filtered = computed(() => {
  const kw = q.value.trim().toLowerCase()
  if (!kw) return ports.value
  return ports.value.filter(p => [p.host, String(p.port), p.service || '', p.banner || ''].join(' ').toLowerCase().includes(kw))
})

async function refresh() {
  try {
    const [st, pr] = await Promise.all([
      RedOps.api(MID, '/scan/status').then((r: Response) => r.json()),
      RedOps.api(MID, '/ports').then((r: Response) => r.json()),
    ])
    scan.value = st.status ?? scan.value
    ports.value = pr.items ?? []
  } catch { /* ignore polling errors */ }
}

function poll() {
  if (timer) clearTimeout(timer)
  const tick = async () => {
    await refresh()
    if (scan.value.running) { timer = setTimeout(tick, 1500) } else { timer = null }
  }
  timer = setTimeout(tick, 800)
}

async function start() {
  if (!targetList.value.length) { RedOps?.toast?.('请先填写扫描目标', 'warn'); return }
  try {
    const res = await RedOps.api(MID, '/scan', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        targets: targetList.value, ports: portSpec.value, portsCustom: portsCustom.value,
        mode: mode.value, proto: proto.value, rate: rate.value,
        concurrency: concurrency.value, timeout: timeout.value,
        discovery: discovery.value, svc: svc.value, banner: banner.value,
      }),
    })
    if (res.status === 409) { RedOps?.toast?.('已有扫描在运行，请先停止', 'warn'); return }
    if (!res.ok) { const j = await res.json().catch(() => ({})); RedOps?.toast?.(j.error || '发起失败', 'err'); return }
    const j = await res.json()
    scan.value = j.status ?? scan.value
    ports.value = []
    RedOps?.toast?.(`已对 ${targetList.value.length} 个目标发起扫描`, 'ok')
    poll()
  } catch (e: any) { RedOps?.toast?.('发起失败: ' + (e?.message ?? e), 'err') }
}

async function stop() {
  try { await RedOps.api(MID, '/scan/stop', { method: 'POST' }); RedOps?.toast?.('已请求停止', 'warn') } catch { /* ignore */ }
}

async function exportAs(fmt: string) {
  try {
    const res = await RedOps.api(MID, `/export?format=${fmt}`)
    if (!res.ok) { RedOps?.toast?.('导出失败', 'err'); return }
    const blob = await res.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = `portscan.${fmt}`
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url)
    RedOps?.toast?.(`已导出 ${fmt.toUpperCase()}`, 'ok')
  } catch (e: any) { RedOps?.toast?.('导出失败: ' + (e?.message ?? e), 'err') }
}

onMounted(async () => { await refresh(); if (scan.value.running) poll() })
onUnmounted(() => { if (timer) clearTimeout(timer) })
</script>

<style scoped>
.pt-targets { width: 100%; resize: vertical; font-family: 'JetBrains Mono', ui-monospace, monospace; font-size: 12.5px; line-height: 1.6; }
.pt-opts { display: flex; align-items: center; gap: 12px; margin-top: 12px; flex-wrap: wrap; }
.pt-opt { display: flex; align-items: center; gap: 8px; font-size: 12.5px; color: var(--rx-mid, #94a3b8); }
.pt-num { width: 84px; }
.pt-check { cursor: pointer; }
.pt-check input { accent-color: var(--rx-cyan, #22d3ee); }
.rx-btn-danger { background: rgba(244, 63, 94, .14); border-color: rgba(244, 63, 94, .4); color: #fda4af; }
.rx-btn-ghost { background: rgba(34, 211, 238, .08); border-color: rgba(34, 211, 238, .28); color: #7dd3fc; font-size: 12px; padding: 5px 10px; }
.rx-btn-ghost:disabled { opacity: .4; cursor: not-allowed; }
.pt-progress { margin-top: 14px; }
.pt-bar { height: 8px; border-radius: 5px; background: rgba(7, 10, 16, .6); overflow: hidden; border: 1px solid var(--rx-line, #1d2533); }
.pt-bar span { display: block; height: 100%; background: linear-gradient(90deg, #22d3ee, #6366f1); transition: width .4s ease; }
.pt-prog-meta { display: flex; justify-content: space-between; font-size: 11.5px; color: var(--rx-dim, #6b7689); margin-top: 6px; }
</style>

// scan-port/web/View.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import {
  Radar, Network, Server, Globe, Activity, Play, Square, RefreshCw, Download,
} from 'lucide-react'
import { Panel, StatCard, Progress } from '@/components/ui'
import { engineGet, enginePost, engineDownload } from '@/lib/engine'
import { ApiError } from '@/lib/api'
import { createTask, updateTask } from '@/lib/tasks'
import TaskList from '@/components/TaskList'

const CAP = 'scan-port'

interface Port {
  host: string
  port: number
  proto: string
  service: string
  banner: string
  osGuess: string
}

interface ScanStatus {
  running: boolean
  phase: string
  total: number
  probed: number
  found: number
  closed: number
  filtered: number
  alive: number
  rate: number
  engine: string
  elapsedMs: number
  target: string
  startedAt: string
  endedAt: string
  err: string
}

type Mode = 'masscan' | 'connect' | 'syn'
type Proto = 'tcp' | 'udp' | 'both'

const ENGINE_LABEL: Record<string, string> = {
  masscan: 'masscan（内嵌·高速）',
  connect: 'connect（纯 Go）',
  syn: 'SYN（半开）',
}

export default function View() {
  const [status, setStatus] = useState<ScanStatus | null>(null)
  const [ports, setPorts] = useState<Port[]>([])

  const [targets, setTargets] = useState('')
  const [portSpec, setPortSpec] = useState('top1000')
  const [portsCustom, setPortsCustom] = useState('22,80,443')
  const [mode, setMode] = useState<Mode>('masscan')
  const [proto, setProto] = useState<Proto>('tcp')
  const [rate, setRate] = useState(1000)
  const [concurrency, setConcurrency] = useState(256)
  const [timeout, setTimeoutMs] = useState(1500)
  const [discovery, setDiscovery] = useState(false)
  const [svc, setSvc] = useState(true)
  const [banner, setBanner] = useState(true)

  const [err, setErr] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [taskReload, setTaskReload] = useState(0)
  const timer = useRef<ReturnType<typeof setInterval> | null>(null)

  const refresh = useCallback(async () => {
    const [st, p] = await Promise.all([
      engineGet<{ status: ScanStatus; id: string }>(CAP, '/scan/status'),
      engineGet<{ items: Port[] }>(CAP, '/ports'),
    ])
    setStatus(st.status)
    setPorts(p.items ?? [])
    return st.status
  }, [])

  // 仅在扫描运行时轮询实时进度/端口（界面展示）。任务台账的进度/结果固化由
  // 后端 reconcile-on-read 负责（读取任务时按 task_id 拉引擎落库结果），本端不镜像。
  const startPolling = useCallback(() => {
    if (timer.current) return
    timer.current = setInterval(async () => {
      try {
        const st = await refresh()
        if (!st.running && timer.current) {
          clearInterval(timer.current); timer.current = null
          setTaskReload((n) => n + 1)
        }
      } catch { /* 轮询瞬时错误忽略 */ }
    }, 1500)
  }, [refresh])

  useEffect(() => {
    refresh().then((st) => { if (st.running) startPolling() }).catch((e) => setErr(String(e?.message ?? e)))
    return () => { if (timer.current) clearInterval(timer.current) }
  }, [refresh, startPolling])

  async function call(fn: () => Promise<unknown>) {
    setBusy(true); setErr(null)
    try { await fn(); await refresh() }
    catch (e) { setErr(e instanceof ApiError ? e.message : String((e as Error)?.message ?? e)) }
    finally { setBusy(false) }
  }

  async function startScan() {
    const list = targets.split('\n').map((t) => t.trim()).filter(Boolean)
    if (!list.length) { setErr('请填写至少一个目标（IP / 域名 / CIDR，每行一个）'); return }
    await call(async () => {
      const params = {
        targets: list, ports: portSpec, portsCustom, mode, proto,
        rate, concurrency, timeout, discovery, svc, banner,
      }
      // 统一 task_id：先向系统申请 id 落台账，再透传给引擎 /invoke。
      const t = await createTask({ capabilityKey: CAP, action: 'scan', params })
      setTaskReload((n) => n + 1)
      try {
        await enginePost(CAP, '/invoke', { taskId: t.id, function: 'scan', params })
      } catch (e) {
        await updateTask(t.id, {
          status: 'failed', error: e instanceof Error ? e.message : String(e),
        }).catch(() => {})
        setTaskReload((n) => n + 1)
        throw e
      }
      startPolling()
    })
  }

  const running = status?.running ?? false
  const pct = status && status.total > 0 ? Math.min(100, Math.round((status.probed / status.total) * 100)) : 0
  const hosts = new Set(ports.map((p) => p.host)).size
  const tcpCount = ports.filter((p) => p.proto === 'tcp').length
  const udpCount = ports.filter((p) => p.proto === 'udp').length

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard label="开放端口" value={ports.length || '—'} icon={<Network size={18} />} />
        <StatCard label="涉及主机" value={hosts || '—'} icon={<Globe size={18} />} />
        <StatCard label="TCP / UDP" value={`${tcpCount} / ${udpCount}`} icon={<Server size={18} />} />
        <StatCard
          label="本次引擎"
          value={status?.engine ? (ENGINE_LABEL[status.engine] ?? status.engine) : '—'}
          icon={<Radar size={18} />}
        />
      </div>

      <Panel title="发起端口扫描" icon={<Radar size={16} />}>
        <div className="space-y-3">
          <textarea
            className="w-full rounded-lg border border-line bg-base-700/60 p-3 font-mono text-sm text-slate-200 outline-none focus:border-cyber"
            rows={3} placeholder="目标，每行一个：192.168.1.0/24 或 example.com 或 10.0.0.5"
            value={targets} onChange={(e) => setTargets(e.target.value)} disabled={running}
          />
          <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
            <label className="flex items-center gap-2">端口
              <select value={portSpec} onChange={(e) => setPortSpec(e.target.value)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                <option value="top100">top100（高频端口）</option>
                <option value="top500">top500（约 370 个）</option>
                <option value="top1000">top1000（推荐）</option>
                <option value="all">全端口（慎用）</option>
                <option value="custom">自定义</option>
              </select>
            </label>
            {portSpec === 'custom' && (
              <label className="flex items-center gap-2">自定义端口
                <input value={portsCustom} onChange={(e) => setPortsCustom(e.target.value)} disabled={running}
                  placeholder="22,80,443,8000-8100"
                  className="w-48 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
              </label>
            )}
            <label className="flex items-center gap-2">引擎
              <select value={mode} onChange={(e) => setMode(e.target.value as Mode)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                <option value="masscan">masscan（高速·需管理员）</option>
                <option value="connect">connect（免提权）</option>
                <option value="syn">SYN（需 npcap）</option>
              </select>
            </label>
            <label className="flex items-center gap-2">协议
              <select value={proto} onChange={(e) => setProto(e.target.value as Proto)} disabled={running}
                className="rounded border border-line bg-base-700/60 px-2 py-1">
                <option value="tcp">TCP</option>
                <option value="udp">UDP</option>
                <option value="both">TCP+UDP</option>
              </select>
            </label>
            <label className="flex items-center gap-2">速率
              <input type="number" min={0} max={100000} value={rate}
                onChange={(e) => setRate(+e.target.value)} disabled={running}
                className="w-24 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">并发
              <input type="number" min={1} max={1024} value={concurrency}
                onChange={(e) => setConcurrency(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">超时ms
              <input type="number" min={100} max={10000} value={timeout}
                onChange={(e) => setTimeoutMs(+e.target.value)} disabled={running}
                className="w-20 rounded border border-line bg-base-700/60 px-2 py-1 font-mono" />
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={discovery} onChange={(e) => setDiscovery(e.target.checked)} disabled={running} />
              存活探测
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={svc} onChange={(e) => setSvc(e.target.checked)} disabled={running} />
              服务识别
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={banner} onChange={(e) => setBanner(e.target.checked)} disabled={running} />
              抓取 Banner
            </label>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {running ? (
              <button onClick={() => call(() => enginePost(CAP, '/scan/stop'))} disabled={busy}
                className="chip border border-sev-high/40 bg-sev-high/10 text-sev-high">
                <Square size={14} /> 停止扫描
              </button>
            ) : (
              <button onClick={startScan} disabled={busy}
                className="chip border border-cyber/40 bg-cyber/10 text-cyber">
                <Play size={14} /> 发起扫描
              </button>
            )}
            <button onClick={() => call(async () => { await refresh() })} disabled={busy}
              className="chip border border-line bg-base-600/60 text-slate-300">
              <RefreshCw size={14} /> 刷新
            </button>
            <div className="ml-auto flex items-center gap-1">
              {(['json', 'csv', 'html'] as const).map((f) => (
                <button key={f} onClick={() => engineDownload(CAP, '/export', `portscan-ports.${f}`, { format: f })}
                  disabled={ports.length === 0}
                  className="chip border border-line bg-base-600/60 text-slate-400">
                  <Download size={14} /> {f.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          {running && (
            <div className="space-y-1">
              <div className="flex justify-between text-xs text-slate-400">
                <span>{status?.phase || '扫描中…'}　{status?.target}</span>
                <span className="font-mono">{status?.probed}/{status?.total}（开放 {status?.found}）</span>
              </div>
              <Progress value={pct} />
            </div>
          )}
          {err && <div className="text-sm text-sev-high">{err}</div>}
        </div>
      </Panel>

      <Panel title={`开放端口（${ports.length}）`} icon={<Activity size={16} />} bodyClass="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-line text-left text-xs text-slate-500">
                <th className="px-4 py-2 font-medium">主机</th>
                <th className="px-4 py-2 font-medium">端口</th>
                <th className="px-4 py-2 font-medium">协议</th>
                <th className="px-4 py-2 font-medium">服务</th>
                <th className="px-4 py-2 font-medium">OS</th>
                <th className="px-4 py-2 font-medium">Banner</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {ports.length === 0 && (
                <tr><td colSpan={6} className="p-6 text-center text-sm text-slate-500">暂无开放端口</td></tr>
              )}
              {ports.map((p, i) => (
                <tr key={`${p.host}/${p.proto}/${p.port}/${i}`} className="hover:bg-base-600/40">
                  <td className="px-4 py-2 font-mono text-slate-300">{p.host}</td>
                  <td className="px-4 py-2 font-mono text-cyber">{p.port}</td>
                  <td className="px-4 py-2">
                    <span className="chip border border-line bg-base-600/60 text-xs text-slate-400">{p.proto}</span>
                  </td>
                  <td className="px-4 py-2 text-slate-300">{p.service || '—'}</td>
                  <td className="px-4 py-2 text-xs text-slate-400">{p.osGuess || '—'}</td>
                  <td className="px-4 py-2 font-mono text-xs text-slate-500">{p.banner || '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      <Panel title="历史任务" icon={<Radar size={16} />} bodyClass="p-3">
        <TaskList params={{ capabilityKey: CAP }} showCapability={false} reloadToken={taskReload}
          emptyHint="暂无任务记录，发起一次扫描后将登记到此。" />
      </Panel>
    </div>
  )
}
